[package]
name = "RustBackend"
version = "0.1.0"
edition = "2024"



#4gQT88rvHr6ay8XvmUUriL5FTjsSuvkvH8ybz3etVLBb


[dependencies]
warp = "0.3"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
once_cell = "1.8"
http = "0.2.12"